config/routes.rb
Rails.application.routes.draw do
  resources :users, except: %i[destroy]

  resources :todos, except: %i[show new]

  resource :session, only: %i[new create destroy]

  resource :password_reset, only: %i[new create edit update]

  root to: "todos#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :require_no_authentication
  before_action :set_user, only: %i[edit update]

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      @user.set_password_reset_token
      PasswordResetMailer.with(user: @user).reset_email.deliver_later
    end
    redirect_to new_session_path, notice: "Password reset instructions have been sent to your email"
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to new_session_path, notice: "Your password has been updated!"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation).merge(skip_old_password: true)
  end

  def set_user
    @user = User.find_by(email: params[:user][:email],
                          password_reset_token: params[:user][:password_reset_token])
    redirect_to(new_session_path, alert: "Could not reset password") unless @user&.password_reset_perion_valid?
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <%= render 'shared/errors', object: @user %>
            <h4 class="text-center my-3 pb-3">Enter new password</h4>
            <div class="form-control mx-auto">
              <%= form_with data: {turbo: false}, model: @user, url: password_reset_path, method: :patch do |form| %>
                <%= form.hidden_field :password_reset_token, value: @user.password_reset_token %>
                <%= form.hidden_field :email, value: @user.email %>

                <%= form.label :password, class: "form-label mt-3" %>
                <%= form.password_field :password, class: "form-control" %>

                <%= form.label :password_confirmation, class: "form-label mt-3" %>
                <%= form.password_field :password_confirmation, class: "form-control" %>
                <div class="text-end">
                  <%= form.submit "Reset my password!", class: "btn btn-primary mt-3 mb-2"%>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/password_resets/new.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <h4 class="text-center my-3 pb-3">Reset password</h4>
            <div class="form-control mx-auto">
              <%= form_with data: {turbo: false}, url: password_reset_path do |form| %>
                <%= form.label :email, class: "form-label mt-3" %>
                <%= form.email_field :email, class: "form-control" %>
                <div class="text-end">
                  <%= form.submit "Submit", class: "btn btn-primary mt-3 mb-2"%>
                </div>
                <div class="text-end"><%= link_to "Back", new_session_path %></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>