config/routes.rb
Rails.application.routes.draw do
  resources :users, except: %i[destroy]

  resources :todos, except: %i[show new]

  resource :session, only: %i[new create destroy]

  resource :password_reset, only: %i[new create edit update]

  root to: "todos#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Recoverable

  attr_accessor :old_password, :skip_old_password

  has_many :todos, dependent: :destroy

  has_secure_password validations: false

  validate :password_presence
  validates :password, confirmation: true, allow_blank: true,
                       length: { minimum: 5, maximum: 50 }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validate :correct_old_password, on: :update, if: -> { password.present? && !skip_old_password }

  private
  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add(:old_password, 'wrong')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :verify_token, only: %i[edit update show]
  before_action :set_user, only: %i[edit update]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: "You have successfully registered!"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Changes has been saved!"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation, :old_password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<div class="form-control mx-auto">
  <%= form_with data: {turbo: false}, model: user do |form| %>
    <%= form.label :name, "Name", class: "form-label" %>
    <%= form.text_field :name, required: true, class: "form-control" %>

    <%= form.label :email, class: "form-label mt-3" %>
    <%= form.email_field :email, class: "form-control" %>
    <% unless user.new_record?%>
      <%= form.label :old_password, "Old password", class: "form-label mt-3" %>
      <%= form.password_field :old_password, class: "form-control" %>
    <% end %>
    <%= form.label :password,(user.new_record? ? "Password" : "New password"), class: "form-label mt-3" %>
    <%= form.password_field :password, class: "form-control" %>

    <%= form.label :password_confirmation,(user.new_record? ? "Password confirmation" : "New password confirmation"),
      class: "form-label mt-3" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>

    <div class="text-end">
      <%= form.submit (user.new_record? ? "Register" : "Save"), class: "btn btn-primary mt-3 mb-2"%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <h4 class="text-center my-3 pb-3">Edit profile</h4>
            <div class="mx-auto">
              <%= render "shared/errors", object: @user %>
            </div>
            <%= render 'form', user: @user %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <h4 class="text-center my-3 pb-3">Registration</h4>
            <div class="mx-auto">
              <%= render "shared/errors", object: @user %>
            </div>
            <%= render 'form', user: @user %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <%= render 'shared/flash' %>
            <h4 class="text-center my-3 pb-3"><%= @user.name %> profile </h4></p>
            <p class="text-center">Name: <%= @user.name %></p>
            <p class="text-center">Email: <%= @user.email %></p>
            <p class="text-center">Todos: <%= @user.todos.count %></p>
            <p class="text-center"><%= link_to "Edit prifole", edit_user_path(@user), class: "text-dark" %></p>
            <p class="text-center"><%= link_to "Home", root_path, class: "text-dark" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>