config/routes.rb
Rails.application.routes.draw do
  resources :users, except: %i[destroy]

  resources :todos, except: %i[show new]

  resource :session, only: %i[new create destroy]

  resource :password_reset, only: %i[new create edit update]

  root to: "todos#index"
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[edit update destroy]
  before_action :verify_token

  def index
    @pagy, @todos = pagy(Todo.where(user_id: current_user.id).order('status', updated_at: :desc), items: 5)
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path, notice: "To do has been created!"
    else
      @pagy, @todos = pagy(Todo.where(user_id: current_user.id).order('status', updated_at: :desc), items: 5)
      render :index
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to root_path, notice: "Changes has been saved!"
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to root_path, notice: "To do has been deleted!"
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :status).merge(user_id: current_user.id)
  end
end

app/views/todos/_form.html.erb
<%= form_with data: {turbo: false}, class: "d-flex flex-fill", model: todo do |form| %>
  <%= form.text_field :title, placeholder: "Enter new to do", required: true, class: "form-control mx-2" %>
  <% if todo.persisted?%>
    <%= form.check_box :status, class: "mx-1" %>
    <%= form.label :status, "Done", class: "form-label mt-2" %>
  <% end %>
  <%= form.submit "Save", class: "btn mx-2 btn-primary"%>
<% end %>

app/views/todos/_todos.html.erb
<% todos.each do |todo| %>
  <tr>
    <td>
      <% if todo.status == true %>
        <input class="form-check-input" type="checkbox" style="background-color: #000000; border-color: #000000" value="" checked disabled>
        <% else %> <input class="form-check-input" type="checkbox" style="background-color: #000000; border-color: #000000" value="" disabled>
      <% end %>
    </td>
    <td><%= truncate (todo.title), length: 50 %></td>
    <td class="text-center">
      <div class="d-inline-block">
        <%= button_to "Edit", edit_todo_path(todo), method: :get, class: "btn btn-sm btn-primary" %>
      </div>
      <div class="d-inline-block">
        <%= button_to "Delete", todo_path(todo),
          data: {turbo_confirm: "Удалить дело?"}, method: :delete, class: "btn btn-sm btn-primary" %>
      </div>
    </td>
  </tr>
<% end %>

app/views/todos/edit.html.erb
 <section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <h4 class="text-center my-3 pb-3">Edit Todo № <%= @todo.id%> </h4>
            <%= render 'form', todo: @todo %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/index.html.erb
<section class="vh-100" style="background-color: #2F4F4F;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">
            <%= render 'shared/flash' %>
            <h4 class="text-center my-3 pb-3">To Do Application</h4>
            <nav class="navbar bg-light">
              <%= render 'form', todo: @todo %>
            </nav>
            <table class="table table-striped mb-4 text-center">
              <thead>
                <tr>
                  <th scope="col">Status</th>
                  <th scope="col">Todo Item</th>
                  <th scope="col" class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                <%= render 'todos', todos: @todos %>
              </tbody>
            </table>
            <nav class="pagination justify-content-center mt-3"><%== pagy_bootstrap_nav @pagy, class: "bg-dark" %></nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>